[project]
name = "nba-trade-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ishaan Singla", email = "cheif.ishaan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
nba-trade-analyzer = "nba_trade_analyzer:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
